import type { Stock, Alert } from "@workspace/api-client-react";

export const mockStockData: Stock[] = [
  {
    ticker: 'TELA',
    company: 'TELA Bio',
    price: 0.83,
    exchange: 'NASDAQ',
    industry: 'MedTech',
    daysUnderOne: 47,
    daysToDeadline: 174,
    bounceProbability: 68,
    delistingRisk: 34,
    complianceScore: 74,
    financialScore: 41,
    operatorScore: 58,
    industryScore: 49,
    patternScore: 66,
    tradabilityScore: 72,
    operatorNote: 'Mixed management record; not a serial destroyer.',
    financialNote: 'Weak profitability, but capital markets access still open.',
    tradeWindow: '7–21 days',
    entryZone: '$0.78–$0.82',
    targetZone: '$0.96–$1.06',
    stopZone: '$0.72',
    status: 'Recovery Candidate',
    volume: '133.6K',
    chart: [
      { d: 'W1', p: 1.34 },
      { d: 'W2', p: 1.12 },
      { d: 'W3', p: 0.98 },
      { d: 'W4', p: 0.88 },
      { d: 'W5', p: 0.84 },
      { d: 'W6', p: 0.79 },
      { d: 'W7', p: 0.76 },
      { d: 'W8', p: 0.83 }
    ]
  },
  {
    ticker: 'GAME',
    company: 'GameSquare',
    price: 0.29,
    exchange: 'NASDAQ',
    industry: 'Media / Esports',
    daysUnderOne: 212,
    daysToDeadline: 167,
    bounceProbability: 39,
    delistingRisk: 77,
    complianceScore: 31,
    financialScore: 26,
    operatorScore: 43,
    industryScore: 45,
    patternScore: 34,
    tradabilityScore: 48,
    operatorNote: 'Late-stage compliance case with extension already used.',
    financialNote: 'Heavily dependent on capital markets support.',
    tradeWindow: '3–10 days',
    entryZone: '$0.26–$0.28',
    targetZone: '$0.34–$0.40',
    stopZone: '$0.23',
    status: 'High Delisting Risk',
    volume: '589K',
    chart: [
      { d: 'W1', p: 0.74 },
      { d: 'W2', p: 0.61 },
      { d: 'W3', p: 0.52 },
      { d: 'W4', p: 0.43 },
      { d: 'W5', p: 0.38 },
      { d: 'W6', p: 0.33 },
      { d: 'W7', p: 0.27 },
      { d: 'W8', p: 0.29 }
    ]
  },
  {
    ticker: 'FFIE',
    company: 'Faraday Future Intelligent Electric',
    price: 0.35,
    exchange: 'NASDAQ',
    industry: 'EV',
    daysUnderOne: 58,
    daysToDeadline: 176,
    bounceProbability: 54,
    delistingRisk: 62,
    complianceScore: 60,
    financialScore: 18,
    operatorScore: 35,
    industryScore: 24,
    patternScore: 59,
    tradabilityScore: 67,
    operatorNote: 'Speculative operator profile with higher pattern risk.',
    financialNote: 'Very weak business quality; movement is mostly capital-market driven.',
    tradeWindow: '2–8 days',
    entryZone: '$0.31–$0.34',
    targetZone: '$0.42–$0.50',
    stopZone: '$0.28',
    status: 'Management Action Likely',
    volume: '235.1M',
    chart: [
      { d: 'W1', p: 1.11 },
      { d: 'W2', p: 0.92 },
      { d: 'W3', p: 0.76 },
      { d: 'W4', p: 0.63 },
      { d: 'W5', p: 0.49 },
      { d: 'W6', p: 0.37 },
      { d: 'W7', p: 0.29 },
      { d: 'W8', p: 0.35 }
    ]
  },
  {
    ticker: 'ALXO',
    company: 'ALX Oncology',
    price: 0.96,
    exchange: 'NASDAQ',
    industry: 'Biotech',
    daysUnderOne: 29,
    daysToDeadline: 205,
    bounceProbability: 71,
    delistingRisk: 28,
    complianceScore: 82,
    financialScore: 44,
    operatorScore: 61,
    industryScore: 22,
    patternScore: 70,
    tradabilityScore: 75,
    operatorNote: 'Cleaner than average setup, but biotech remains structurally risky.',
    financialNote: 'Cash exists, but survival still relies on pipeline outcomes.',
    tradeWindow: '5–15 days',
    entryZone: '$0.92–$0.95',
    targetZone: '$1.05–$1.15',
    stopZone: '$0.88',
    status: 'Recovery Candidate',
    volume: '1.8M',
    chart: [
      { d: 'W1', p: 1.48 },
      { d: 'W2', p: 1.27 },
      { d: 'W3', p: 1.14 },
      { d: 'W4', p: 1.03 },
      { d: 'W5', p: 0.98 },
      { d: 'W6', p: 0.94 },
      { d: 'W7', p: 0.93 },
      { d: 'W8', p: 0.96 }
    ]
  },
  {
    ticker: 'MVST',
    company: 'Microvast Holdings',
    price: 0.52,
    exchange: 'NASDAQ',
    industry: 'EV Battery',
    daysUnderOne: 63,
    daysToDeadline: 189,
    bounceProbability: 65,
    delistingRisk: 41,
    complianceScore: 68,
    financialScore: 35,
    operatorScore: 54,
    industryScore: 58,
    patternScore: 62,
    tradabilityScore: 70,
    operatorNote: 'Management actively pursuing revenue contracts; not passive.',
    financialNote: 'Recurring revenue growing, but still burning cash.',
    tradeWindow: '7–18 days',
    entryZone: '$0.48–$0.51',
    targetZone: '$0.62–$0.72',
    stopZone: '$0.43',
    status: 'Recovery Candidate',
    volume: '4.2M',
    chart: [
      { d: 'W1', p: 1.02 },
      { d: 'W2', p: 0.88 },
      { d: 'W3', p: 0.79 },
      { d: 'W4', p: 0.68 },
      { d: 'W5', p: 0.61 },
      { d: 'W6', p: 0.55 },
      { d: 'W7', p: 0.49 },
      { d: 'W8', p: 0.52 }
    ]
  },
  {
    ticker: 'WKHS',
    company: 'Workhorse Group',
    price: 0.47,
    exchange: 'NASDAQ',
    industry: 'EV Delivery',
    daysUnderOne: 89,
    daysToDeadline: 161,
    bounceProbability: 58,
    delistingRisk: 52,
    complianceScore: 55,
    financialScore: 27,
    operatorScore: 48,
    industryScore: 44,
    patternScore: 56,
    tradabilityScore: 63,
    operatorNote: 'New CEO improving execution; execution risk still present.',
    financialNote: 'Burning cash with limited near-term revenue visibility.',
    tradeWindow: '5–12 days',
    entryZone: '$0.43–$0.46',
    targetZone: '$0.56–$0.65',
    stopZone: '$0.38',
    status: 'Management Action Likely',
    volume: '3.7M',
    chart: [
      { d: 'W1', p: 0.93 },
      { d: 'W2', p: 0.79 },
      { d: 'W3', p: 0.69 },
      { d: 'W4', p: 0.59 },
      { d: 'W5', p: 0.53 },
      { d: 'W6', p: 0.48 },
      { d: 'W7', p: 0.44 },
      { d: 'W8', p: 0.47 }
    ]
  },
  {
    ticker: 'BNGO',
    company: 'Bionano Genomics',
    price: 0.38,
    exchange: 'NASDAQ',
    industry: 'Genomics Tech',
    daysUnderOne: 134,
    daysToDeadline: 148,
    bounceProbability: 44,
    delistingRisk: 68,
    complianceScore: 42,
    financialScore: 22,
    operatorScore: 39,
    industryScore: 36,
    patternScore: 41,
    tradabilityScore: 55,
    operatorNote: 'Revenue not yet sufficient to support current cost base.',
    financialNote: 'Heavy dilution history; equity raise likely needed.',
    tradeWindow: '3–9 days',
    entryZone: '$0.34–$0.37',
    targetZone: '$0.46–$0.54',
    stopZone: '$0.29',
    status: 'High Delisting Risk',
    volume: '7.8M',
    chart: [
      { d: 'W1', p: 0.88 },
      { d: 'W2', p: 0.72 },
      { d: 'W3', p: 0.61 },
      { d: 'W4', p: 0.52 },
      { d: 'W5', p: 0.46 },
      { d: 'W6', p: 0.41 },
      { d: 'W7', p: 0.36 },
      { d: 'W8', p: 0.38 }
    ]
  },
  {
    ticker: 'SNDL',
    company: 'SNDL Inc',
    price: 0.72,
    exchange: 'NASDAQ',
    industry: 'Cannabis',
    daysUnderOne: 71,
    daysToDeadline: 191,
    bounceProbability: 61,
    delistingRisk: 44,
    complianceScore: 63,
    financialScore: 38,
    operatorScore: 52,
    industryScore: 31,
    patternScore: 60,
    tradabilityScore: 68,
    operatorNote: 'Operator has shown willingness to restructure to stay listed.',
    financialNote: 'Retail cannabis revenue stabilizing; path to profitability unclear.',
    tradeWindow: '6–14 days',
    entryZone: '$0.67–$0.71',
    targetZone: '$0.84–$0.95',
    stopZone: '$0.61',
    status: 'Recovery Candidate',
    volume: '2.1M',
    chart: [
      { d: 'W1', p: 1.18 },
      { d: 'W2', p: 1.03 },
      { d: 'W3', p: 0.91 },
      { d: 'W4', p: 0.82 },
      { d: 'W5', p: 0.77 },
      { d: 'W6', p: 0.74 },
      { d: 'W7', p: 0.70 },
      { d: 'W8', p: 0.72 }
    ]
  },
  {
    ticker: 'MULN',
    company: 'Mullen Automotive',
    price: 0.18,
    exchange: 'NASDAQ',
    industry: 'EV Trucks',
    daysUnderOne: 287,
    daysToDeadline: 94,
    bounceProbability: 22,
    delistingRisk: 91,
    complianceScore: 18,
    financialScore: 11,
    operatorScore: 24,
    industryScore: 28,
    patternScore: 20,
    tradabilityScore: 34,
    operatorNote: 'Serial diluter with poor capital allocation history.',
    financialNote: 'Minimal revenue; survival entirely dependent on equity markets.',
    tradeWindow: '1–4 days',
    entryZone: '$0.16–$0.18',
    targetZone: '$0.22–$0.27',
    stopZone: '$0.13',
    status: 'High Delisting Risk',
    volume: '41.2M',
    chart: [
      { d: 'W1', p: 0.61 },
      { d: 'W2', p: 0.48 },
      { d: 'W3', p: 0.38 },
      { d: 'W4', p: 0.29 },
      { d: 'W5', p: 0.24 },
      { d: 'W6', p: 0.21 },
      { d: 'W7', p: 0.17 },
      { d: 'W8', p: 0.18 }
    ]
  },
  {
    ticker: 'HYMC',
    company: 'Hycroft Mining',
    price: 0.31,
    exchange: 'NASDAQ',
    industry: 'Gold / Silver',
    daysUnderOne: 156,
    daysToDeadline: 132,
    bounceProbability: 46,
    delistingRisk: 63,
    complianceScore: 47,
    financialScore: 31,
    operatorScore: 44,
    industryScore: 52,
    patternScore: 45,
    tradabilityScore: 51,
    operatorNote: 'Mining operations on hold; asset value provides partial floor.',
    financialNote: 'Cash-constrained; gold price sensitivity creates binary risk.',
    tradeWindow: '4–11 days',
    entryZone: '$0.28–$0.31',
    targetZone: '$0.38–$0.45',
    stopZone: '$0.24',
    status: 'Watch',
    volume: '892K',
    chart: [
      { d: 'W1', p: 0.67 },
      { d: 'W2', p: 0.56 },
      { d: 'W3', p: 0.48 },
      { d: 'W4', p: 0.41 },
      { d: 'W5', p: 0.37 },
      { d: 'W6', p: 0.34 },
      { d: 'W7', p: 0.29 },
      { d: 'W8', p: 0.31 }
    ]
  },
  {
    ticker: 'CLOV',
    company: 'Clover Health Investments',
    price: 0.44,
    exchange: 'NASDAQ',
    industry: 'Insurtech',
    daysUnderOne: 102,
    daysToDeadline: 158,
    bounceProbability: 52,
    delistingRisk: 57,
    complianceScore: 53,
    financialScore: 33,
    operatorScore: 47,
    industryScore: 40,
    patternScore: 51,
    tradabilityScore: 59,
    operatorNote: 'Medicare Advantage model faces structural headwinds.',
    financialNote: 'Improving medical loss ratio, but scale remains insufficient.',
    tradeWindow: '4–12 days',
    entryZone: '$0.40–$0.43',
    targetZone: '$0.52–$0.61',
    stopZone: '$0.35',
    status: 'Watch',
    volume: '5.4M',
    chart: [
      { d: 'W1', p: 0.87 },
      { d: 'W2', p: 0.74 },
      { d: 'W3', p: 0.64 },
      { d: 'W4', p: 0.56 },
      { d: 'W5', p: 0.51 },
      { d: 'W6', p: 0.47 },
      { d: 'W7', p: 0.42 },
      { d: 'W8', p: 0.44 }
    ]
  },
  {
    ticker: 'AQST',
    company: 'Aquestive Therapeutics',
    price: 0.61,
    exchange: 'NASDAQ',
    industry: 'Drug Delivery',
    daysUnderOne: 55,
    daysToDeadline: 197,
    bounceProbability: 63,
    delistingRisk: 39,
    complianceScore: 67,
    financialScore: 40,
    operatorScore: 55,
    industryScore: 47,
    patternScore: 61,
    tradabilityScore: 66,
    operatorNote: 'FDA-cleared product provides near-term revenue anchor.',
    financialNote: 'Commercialization costs remain elevated; profitability 12–18 months out.',
    tradeWindow: '6–16 days',
    entryZone: '$0.57–$0.60',
    targetZone: '$0.72–$0.82',
    stopZone: '$0.52',
    status: 'Recovery Candidate',
    volume: '742K',
    chart: [
      { d: 'W1', p: 1.09 },
      { d: 'W2', p: 0.94 },
      { d: 'W3', p: 0.83 },
      { d: 'W4', p: 0.74 },
      { d: 'W5', p: 0.68 },
      { d: 'W6', p: 0.64 },
      { d: 'W7', p: 0.59 },
      { d: 'W8', p: 0.61 }
    ]
  },
  {
    ticker: 'TELL',
    company: 'Tellurian Inc',
    price: 0.39,
    exchange: 'NASDAQ',
    industry: 'LNG / Gas',
    daysUnderOne: 118,
    daysToDeadline: 144,
    bounceProbability: 48,
    delistingRisk: 59,
    complianceScore: 49,
    financialScore: 29,
    operatorScore: 42,
    industryScore: 55,
    patternScore: 47,
    tradabilityScore: 54,
    operatorNote: 'Project financing remains the key gating factor.',
    financialNote: 'Significant debt load; LNG project viability is price-sensitive.',
    tradeWindow: '3–10 days',
    entryZone: '$0.35–$0.38',
    targetZone: '$0.47–$0.55',
    stopZone: '$0.30',
    status: 'Watch',
    volume: '6.9M',
    chart: [
      { d: 'W1', p: 0.79 },
      { d: 'W2', p: 0.66 },
      { d: 'W3', p: 0.56 },
      { d: 'W4', p: 0.49 },
      { d: 'W5', p: 0.44 },
      { d: 'W6', p: 0.41 },
      { d: 'W7', p: 0.37 },
      { d: 'W8', p: 0.39 }
    ]
  },
  {
    ticker: 'KNDI',
    company: 'Kandi Technologies',
    price: 0.43,
    exchange: 'NASDAQ',
    industry: 'EV Micro',
    daysUnderOne: 77,
    daysToDeadline: 183,
    bounceProbability: 57,
    delistingRisk: 48,
    complianceScore: 58,
    financialScore: 36,
    operatorScore: 50,
    industryScore: 41,
    patternScore: 55,
    tradabilityScore: 61,
    operatorNote: 'China-based operations create regulatory overhang for US listing.',
    financialNote: 'Revenue visible but growth stalled; margins thin.',
    tradeWindow: '5–13 days',
    entryZone: '$0.39–$0.42',
    targetZone: '$0.51–$0.60',
    stopZone: '$0.34',
    status: 'Watch',
    volume: '1.3M',
    chart: [
      { d: 'W1', p: 0.84 },
      { d: 'W2', p: 0.72 },
      { d: 'W3', p: 0.63 },
      { d: 'W4', p: 0.55 },
      { d: 'W5', p: 0.50 },
      { d: 'W6', p: 0.46 },
      { d: 'W7', p: 0.41 },
      { d: 'W8', p: 0.43 }
    ]
  },
  {
    ticker: 'IMMP',
    company: 'Immutep Ltd',
    price: 0.29,
    exchange: 'NASDAQ',
    industry: 'Immunology',
    daysUnderOne: 143,
    daysToDeadline: 137,
    bounceProbability: 42,
    delistingRisk: 66,
    complianceScore: 44,
    financialScore: 24,
    operatorScore: 40,
    industryScore: 33,
    patternScore: 39,
    tradabilityScore: 50,
    operatorNote: 'Clinical-stage with no approved products; binary catalyst risk.',
    financialNote: 'Runway under 18 months without additional financing.',
    tradeWindow: '2–7 days',
    entryZone: '$0.26–$0.29',
    targetZone: '$0.35–$0.42',
    stopZone: '$0.22',
    status: 'High Delisting Risk',
    volume: '1.6M',
    chart: [
      { d: 'W1', p: 0.69 },
      { d: 'W2', p: 0.57 },
      { d: 'W3', p: 0.48 },
      { d: 'W4', p: 0.40 },
      { d: 'W5', p: 0.35 },
      { d: 'W6', p: 0.32 },
      { d: 'W7', p: 0.27 },
      { d: 'W8', p: 0.29 }
    ]
  },
  {
    ticker: 'DPRO',
    company: 'Draganfly Inc',
    price: 0.36,
    exchange: 'NASDAQ',
    industry: 'Drones',
    daysUnderOne: 98,
    daysToDeadline: 162,
    bounceProbability: 50,
    delistingRisk: 55,
    complianceScore: 51,
    financialScore: 30,
    operatorScore: 46,
    industryScore: 48,
    patternScore: 49,
    tradabilityScore: 56,
    operatorNote: 'Government contracts provide some revenue base; execution uncertain.',
    financialNote: 'Small revenue relative to expenses; equity raises likely.',
    tradeWindow: '4–11 days',
    entryZone: '$0.32–$0.35',
    targetZone: '$0.43–$0.51',
    stopZone: '$0.27',
    status: 'Watch',
    volume: '487K',
    chart: [
      { d: 'W1', p: 0.74 },
      { d: 'W2', p: 0.62 },
      { d: 'W3', p: 0.53 },
      { d: 'W4', p: 0.46 },
      { d: 'W5', p: 0.41 },
      { d: 'W6', p: 0.38 },
      { d: 'W7', p: 0.34 },
      { d: 'W8', p: 0.36 }
    ]
  },
  {
    ticker: 'GORO',
    company: 'Gold Resource Corp',
    price: 0.58,
    exchange: 'NYSE A',
    industry: 'Gold Mining',
    daysUnderOne: 44,
    daysToDeadline: 198,
    bounceProbability: 66,
    delistingRisk: 36,
    complianceScore: 71,
    financialScore: 43,
    operatorScore: 57,
    industryScore: 60,
    patternScore: 64,
    tradabilityScore: 69,
    operatorNote: 'Mining operator with track record of production; cost management improving.',
    financialNote: 'Gold-price leverage present; near-term cash flows depend on operations.',
    tradeWindow: '7–17 days',
    entryZone: '$0.54–$0.57',
    targetZone: '$0.68–$0.78',
    stopZone: '$0.49',
    status: 'Recovery Candidate',
    volume: '1.1M',
    chart: [
      { d: 'W1', p: 1.04 },
      { d: 'W2', p: 0.90 },
      { d: 'W3', p: 0.80 },
      { d: 'W4', p: 0.72 },
      { d: 'W5', p: 0.66 },
      { d: 'W6', p: 0.62 },
      { d: 'W7', p: 0.56 },
      { d: 'W8', p: 0.58 }
    ]
  },
  {
    ticker: 'CTXR',
    company: 'Citius Pharmaceuticals',
    price: 0.68,
    exchange: 'NASDAQ',
    industry: 'Specialty Pharma',
    daysUnderOne: 38,
    daysToDeadline: 207,
    bounceProbability: 72,
    delistingRisk: 30,
    complianceScore: 76,
    financialScore: 45,
    operatorScore: 62,
    industryScore: 50,
    patternScore: 69,
    tradabilityScore: 74,
    operatorNote: 'NDA filed product provides near-term commercial catalyst.',
    financialNote: 'Pre-commercial; runway sufficient for 12 months post-approval.',
    tradeWindow: '8–20 days',
    entryZone: '$0.63–$0.67',
    targetZone: '$0.80–$0.91',
    stopZone: '$0.57',
    status: 'Recovery Candidate',
    volume: '2.8M',
    chart: [
      { d: 'W1', p: 1.21 },
      { d: 'W2', p: 1.04 },
      { d: 'W3', p: 0.91 },
      { d: 'W4', p: 0.82 },
      { d: 'W5', p: 0.76 },
      { d: 'W6', p: 0.72 },
      { d: 'W7', p: 0.65 },
      { d: 'W8', p: 0.68 }
    ]
  },
  {
    ticker: 'ATER',
    company: 'Aterian Inc',
    price: 0.32,
    exchange: 'NASDAQ',
    industry: 'E-commerce',
    daysUnderOne: 167,
    daysToDeadline: 123,
    bounceProbability: 36,
    delistingRisk: 73,
    complianceScore: 36,
    financialScore: 23,
    operatorScore: 38,
    industryScore: 42,
    patternScore: 33,
    tradabilityScore: 46,
    operatorNote: 'Platform restructuring has not yet translated to revenue growth.',
    financialNote: 'High inventory risk and declining top-line trend.',
    tradeWindow: '2–8 days',
    entryZone: '$0.28–$0.31',
    targetZone: '$0.38–$0.45',
    stopZone: '$0.24',
    status: 'High Delisting Risk',
    volume: '3.3M',
    chart: [
      { d: 'W1', p: 0.81 },
      { d: 'W2', p: 0.67 },
      { d: 'W3', p: 0.56 },
      { d: 'W4', p: 0.47 },
      { d: 'W5', p: 0.41 },
      { d: 'W6', p: 0.37 },
      { d: 'W7', p: 0.30 },
      { d: 'W8', p: 0.32 }
    ]
  },
  {
    ticker: 'LIQT',
    company: 'LiqTech International',
    price: 0.46,
    exchange: 'NASDAQ',
    industry: 'Filtration',
    daysUnderOne: 81,
    daysToDeadline: 171,
    bounceProbability: 55,
    delistingRisk: 50,
    complianceScore: 56,
    financialScore: 34,
    operatorScore: 49,
    industryScore: 53,
    patternScore: 54,
    tradabilityScore: 60,
    operatorNote: 'Niche industrial market with defensible product position.',
    financialNote: 'Revenue trajectory positive but slow; margins improving gradually.',
    tradeWindow: '5–14 days',
    entryZone: '$0.42–$0.45',
    targetZone: '$0.54–$0.63',
    stopZone: '$0.36',
    status: 'Watch',
    volume: '334K',
    chart: [
      { d: 'W1', p: 0.88 },
      { d: 'W2', p: 0.76 },
      { d: 'W3', p: 0.67 },
      { d: 'W4', p: 0.59 },
      { d: 'W5', p: 0.53 },
      { d: 'W6', p: 0.49 },
      { d: 'W7', p: 0.44 },
      { d: 'W8', p: 0.46 }
    ]
  },
  {
    ticker: 'GLYC',
    company: 'GlycoMimetics Inc',
    price: 0.53,
    exchange: 'NASDAQ',
    industry: 'Biotech',
    daysUnderOne: 66,
    daysToDeadline: 186,
    bounceProbability: 60,
    delistingRisk: 45,
    complianceScore: 62,
    financialScore: 37,
    operatorScore: 53,
    industryScore: 35,
    patternScore: 58,
    tradabilityScore: 64,
    operatorNote: 'Clinical data upcoming; management has clear near-term catalyst.',
    financialNote: 'Cash provides 12-month runway; bridge financing possible.',
    tradeWindow: '5–15 days',
    entryZone: '$0.49–$0.52',
    targetZone: '$0.63–$0.72',
    stopZone: '$0.43',
    status: 'Recovery Candidate',
    volume: '618K',
    chart: [
      { d: 'W1', p: 0.97 },
      { d: 'W2', p: 0.83 },
      { d: 'W3', p: 0.73 },
      { d: 'W4', p: 0.64 },
      { d: 'W5', p: 0.59 },
      { d: 'W6', p: 0.55 },
      { d: 'W7', p: 0.51 },
      { d: 'W8', p: 0.53 }
    ]
  },
  {
    ticker: 'MRIN',
    company: 'Marin Software Inc',
    price: 0.57,
    exchange: 'NASDAQ',
    industry: 'Ad Tech',
    daysUnderOne: 53,
    daysToDeadline: 195,
    bounceProbability: 64,
    delistingRisk: 38,
    complianceScore: 66,
    financialScore: 42,
    operatorScore: 56,
    industryScore: 44,
    patternScore: 63,
    tradabilityScore: 67,
    operatorNote: 'SaaS pivot underway; ARR growth encouraging but from small base.',
    financialNote: 'Lean cost structure; profitability milestone achievable this year.',
    tradeWindow: '6–16 days',
    entryZone: '$0.53–$0.56',
    targetZone: '$0.67–$0.76',
    stopZone: '$0.48',
    status: 'Recovery Candidate',
    volume: '289K',
    chart: [
      { d: 'W1', p: 1.04 },
      { d: 'W2', p: 0.90 },
      { d: 'W3', p: 0.80 },
      { d: 'W4', p: 0.71 },
      { d: 'W5', p: 0.66 },
      { d: 'W6', p: 0.61 },
      { d: 'W7', p: 0.55 },
      { d: 'W8', p: 0.57 }
    ]
  },
  {
    ticker: 'TRVN',
    company: 'Trevena Inc',
    price: 0.62,
    exchange: 'NASDAQ',
    industry: 'CNS Pharma',
    daysUnderOne: 49,
    daysToDeadline: 193,
    bounceProbability: 67,
    delistingRisk: 35,
    complianceScore: 70,
    financialScore: 39,
    operatorScore: 57,
    industryScore: 46,
    patternScore: 65,
    tradabilityScore: 71,
    operatorNote: 'FDA-approved product OLINVYK now in commercial launch phase.',
    financialNote: 'Revenue ramping but still below breakeven; cash adequate near-term.',
    tradeWindow: '7–17 days',
    entryZone: '$0.58–$0.61',
    targetZone: '$0.73–$0.83',
    stopZone: '$0.52',
    status: 'Recovery Candidate',
    volume: '1.4M',
    chart: [
      { d: 'W1', p: 1.12 },
      { d: 'W2', p: 0.96 },
      { d: 'W3', p: 0.85 },
      { d: 'W4', p: 0.76 },
      { d: 'W5', p: 0.70 },
      { d: 'W6', p: 0.65 },
      { d: 'W7', p: 0.60 },
      { d: 'W8', p: 0.62 }
    ]
  },
  {
    ticker: 'GFAI',
    company: 'Guardforce AI Co',
    price: 0.27,
    exchange: 'NASDAQ',
    industry: 'AI Security',
    daysUnderOne: 198,
    daysToDeadline: 112,
    bounceProbability: 31,
    delistingRisk: 80,
    complianceScore: 28,
    financialScore: 18,
    operatorScore: 32,
    industryScore: 37,
    patternScore: 29,
    tradabilityScore: 40,
    operatorNote: 'Foreign private issuer; governance disclosure limited.',
    financialNote: 'Revenue declining; cost structure not viable at current scale.',
    tradeWindow: '1–5 days',
    entryZone: '$0.24–$0.27',
    targetZone: '$0.32–$0.38',
    stopZone: '$0.20',
    status: 'High Delisting Risk',
    volume: '2.2M',
    chart: [
      { d: 'W1', p: 0.72 },
      { d: 'W2', p: 0.58 },
      { d: 'W3', p: 0.47 },
      { d: 'W4', p: 0.38 },
      { d: 'W5', p: 0.33 },
      { d: 'W6', p: 0.29 },
      { d: 'W7', p: 0.25 },
      { d: 'W8', p: 0.27 }
    ]
  },
  {
    ticker: 'BRTX',
    company: 'BioRestorative Therapies',
    price: 0.33,
    exchange: 'NASDAQ',
    industry: 'Regen Medicine',
    daysUnderOne: 124,
    daysToDeadline: 146,
    bounceProbability: 43,
    delistingRisk: 65,
    complianceScore: 45,
    financialScore: 25,
    operatorScore: 41,
    industryScore: 34,
    patternScore: 40,
    tradabilityScore: 49,
    operatorNote: 'Phase 2 trial data expected; positive result could be a catalyst.',
    financialNote: 'Very limited cash; another capital raise is likely.',
    tradeWindow: '2–8 days',
    entryZone: '$0.29–$0.32',
    targetZone: '$0.40–$0.47',
    stopZone: '$0.25',
    status: 'High Delisting Risk',
    volume: '1.8M',
    chart: [
      { d: 'W1', p: 0.75 },
      { d: 'W2', p: 0.62 },
      { d: 'W3', p: 0.52 },
      { d: 'W4', p: 0.44 },
      { d: 'W5', p: 0.39 },
      { d: 'W6', p: 0.35 },
      { d: 'W7', p: 0.31 },
      { d: 'W8', p: 0.33 }
    ]
  },
  {
    ticker: 'WRAP',
    company: 'Wrap Technologies',
    price: 0.64,
    exchange: 'NASDAQ',
    industry: 'Law Enforcement Tech',
    daysUnderOne: 42,
    daysToDeadline: 200,
    bounceProbability: 69,
    delistingRisk: 32,
    complianceScore: 73,
    financialScore: 43,
    operatorScore: 60,
    industryScore: 51,
    patternScore: 67,
    tradabilityScore: 72,
    operatorNote: 'Government procurement cycles provide visible order pipeline.',
    financialNote: 'Growing revenue; breakeven within 2 years at current trajectory.',
    tradeWindow: '7–18 days',
    entryZone: '$0.60–$0.63',
    targetZone: '$0.75–$0.86',
    stopZone: '$0.54',
    status: 'Recovery Candidate',
    volume: '423K',
    chart: [
      { d: 'W1', p: 1.14 },
      { d: 'W2', p: 0.99 },
      { d: 'W3', p: 0.87 },
      { d: 'W4', p: 0.78 },
      { d: 'W5', p: 0.73 },
      { d: 'W6', p: 0.68 },
      { d: 'W7', p: 0.62 },
      { d: 'W8', p: 0.64 }
    ]
  },
  {
    ticker: 'SEED',
    company: 'Origin Agritech',
    price: 0.41,
    exchange: 'NASDAQ',
    industry: 'Agri Tech',
    daysUnderOne: 109,
    daysToDeadline: 151,
    bounceProbability: 49,
    delistingRisk: 58,
    complianceScore: 50,
    financialScore: 31,
    operatorScore: 45,
    industryScore: 46,
    patternScore: 48,
    tradabilityScore: 53,
    operatorNote: 'China-based agri-biotech; IP and market position reasonably defensible.',
    financialNote: 'Seasonal revenue patterns complicate cash flow visibility.',
    tradeWindow: '4–11 days',
    entryZone: '$0.37–$0.40',
    targetZone: '$0.49–$0.57',
    stopZone: '$0.32',
    status: 'Watch',
    volume: '156K',
    chart: [
      { d: 'W1', p: 0.82 },
      { d: 'W2', p: 0.70 },
      { d: 'W3', p: 0.60 },
      { d: 'W4', p: 0.52 },
      { d: 'W5', p: 0.47 },
      { d: 'W6', p: 0.44 },
      { d: 'W7', p: 0.39 },
      { d: 'W8', p: 0.41 }
    ]
  },
  {
    ticker: 'CLNN',
    company: 'Clene Inc',
    price: 0.47,
    exchange: 'NASDAQ',
    industry: 'Biotech',
    daysUnderOne: 75,
    daysToDeadline: 179,
    bounceProbability: 56,
    delistingRisk: 49,
    complianceScore: 57,
    financialScore: 35,
    operatorScore: 51,
    industryScore: 38,
    patternScore: 54,
    tradabilityScore: 61,
    operatorNote: 'Phase 3 ALS trial readout is near-term binary catalyst.',
    financialNote: 'Sufficient cash for 12 months; outcome-dependent thereafter.',
    tradeWindow: '5–13 days',
    entryZone: '$0.43–$0.46',
    targetZone: '$0.56–$0.64',
    stopZone: '$0.37',
    status: 'Watch',
    volume: '912K',
    chart: [
      { d: 'W1', p: 0.91 },
      { d: 'W2', p: 0.78 },
      { d: 'W3', p: 0.68 },
      { d: 'W4', p: 0.59 },
      { d: 'W5', p: 0.54 },
      { d: 'W6', p: 0.50 },
      { d: 'W7', p: 0.45 },
      { d: 'W8', p: 0.47 }
    ]
  },
  {
    ticker: 'INPX',
    company: 'Inpixon Inc',
    price: 0.34,
    exchange: 'NASDAQ',
    industry: 'Indoor Intelligence',
    daysUnderOne: 188,
    daysToDeadline: 122,
    bounceProbability: 37,
    delistingRisk: 72,
    complianceScore: 37,
    financialScore: 22,
    operatorScore: 37,
    industryScore: 43,
    patternScore: 35,
    tradabilityScore: 44,
    operatorNote: 'Frequent reverse splits signal structural weakness.',
    financialNote: 'SaaS revenue small; acquisition strategy not yet proven accretive.',
    tradeWindow: '2–7 days',
    entryZone: '$0.30–$0.33',
    targetZone: '$0.40–$0.47',
    stopZone: '$0.26',
    status: 'High Delisting Risk',
    volume: '3.1M',
    chart: [
      { d: 'W1', p: 0.78 },
      { d: 'W2', p: 0.64 },
      { d: 'W3', p: 0.53 },
      { d: 'W4', p: 0.45 },
      { d: 'W5', p: 0.40 },
      { d: 'W6', p: 0.37 },
      { d: 'W7', p: 0.32 },
      { d: 'W8', p: 0.34 }
    ]
  },
  {
    ticker: 'CELZ',
    company: 'Creative Medical Technology',
    price: 0.55,
    exchange: 'NASDAQ',
    industry: 'Biotech',
    daysUnderOne: 57,
    daysToDeadline: 192,
    bounceProbability: 62,
    delistingRisk: 42,
    complianceScore: 65,
    financialScore: 38,
    operatorScore: 54,
    industryScore: 36,
    patternScore: 60,
    tradabilityScore: 65,
    operatorNote: 'Stem cell platform with multiple clinical programs in progress.',
    financialNote: 'Pre-revenue; financing runway through next milestone.',
    tradeWindow: '6–15 days',
    entryZone: '$0.51–$0.54',
    targetZone: '$0.65–$0.74',
    stopZone: '$0.45',
    status: 'Recovery Candidate',
    volume: '2.5M',
    chart: [
      { d: 'W1', p: 1.01 },
      { d: 'W2', p: 0.87 },
      { d: 'W3', p: 0.77 },
      { d: 'W4', p: 0.68 },
      { d: 'W5', p: 0.63 },
      { d: 'W6', p: 0.58 },
      { d: 'W7', p: 0.53 },
      { d: 'W8', p: 0.55 }
    ]
  },
  {
    ticker: 'PULM',
    company: 'Pulmatrix Inc',
    price: 0.42,
    exchange: 'NASDAQ',
    industry: 'Respiratory',
    daysUnderOne: 91,
    daysToDeadline: 165,
    bounceProbability: 53,
    delistingRisk: 53,
    complianceScore: 54,
    financialScore: 33,
    operatorScore: 47,
    industryScore: 39,
    patternScore: 52,
    tradabilityScore: 58,
    operatorNote: 'Inhaled antifungal pipeline differentiated; partnering discussions active.',
    financialNote: 'Cash burn moderate; next financing event within 12 months.',
    tradeWindow: '4–12 days',
    entryZone: '$0.38–$0.41',
    targetZone: '$0.50–$0.58',
    stopZone: '$0.33',
    status: 'Watch',
    volume: '678K',
    chart: [
      { d: 'W1', p: 0.83 },
      { d: 'W2', p: 0.71 },
      { d: 'W3', p: 0.62 },
      { d: 'W4', p: 0.54 },
      { d: 'W5', p: 0.49 },
      { d: 'W6', p: 0.46 },
      { d: 'W7', p: 0.40 },
      { d: 'W8', p: 0.42 }
    ]
  },
  {
    ticker: 'IMPP',
    company: 'Imperial Petroleum Inc',
    price: 0.69,
    exchange: 'NASDAQ',
    industry: 'Tanker Shipping',
    daysUnderOne: 36,
    daysToDeadline: 204,
    bounceProbability: 70,
    delistingRisk: 31,
    complianceScore: 72,
    financialScore: 46,
    operatorScore: 59,
    industryScore: 57,
    patternScore: 68,
    tradabilityScore: 73,
    operatorNote: 'Fleet expansion in progress; tanker rates currently supportive.',
    financialNote: 'Revenue-generating; profitability tied to tanker rate environment.',
    tradeWindow: '8–19 days',
    entryZone: '$0.64–$0.68',
    targetZone: '$0.81–$0.92',
    stopZone: '$0.58',
    status: 'Recovery Candidate',
    volume: '4.6M',
    chart: [
      { d: 'W1', p: 1.16 },
      { d: 'W2', p: 1.01 },
      { d: 'W3', p: 0.89 },
      { d: 'W4', p: 0.80 },
      { d: 'W5', p: 0.75 },
      { d: 'W6', p: 0.71 },
      { d: 'W7', p: 0.67 },
      { d: 'W8', p: 0.69 }
    ]
  }
];

export const mockAlerts: Alert[] = [
  { id: '1', ticker: 'ALXO', message: 'ALXO moved within 4% of the $1 recovery line', severity: 'warning', createdAt: new Date().toISOString() },
  { id: '2', ticker: 'FFIE', message: 'FFIE volume expanded more than 2.5x average', severity: 'info', createdAt: new Date().toISOString() },
  { id: '3', ticker: 'GAME', message: 'GAME remains late-stage after extension window', severity: 'critical', createdAt: new Date().toISOString() },
  { id: '4', ticker: 'TELA', message: 'TELA created a tighter support band near $0.78', severity: 'info', createdAt: new Date().toISOString() }
];

export const mockWatchlist = ['TELA', 'ALXO'];
