import type { Stock, Alert } from "@workspace/api-client-react";

export const mockStockData: Stock[] = [
  {
    ticker: 'TELA',
    company: 'TELA Bio',
    price: 0.83,
    exchange: 'NASDAQ',
    industry: 'MedTech',
    daysUnderOne: 47,
    daysToDeadline: 174,
    bounceProbability: 68,
    delistingRisk: 34,
    complianceScore: 74,
    financialScore: 41,
    operatorScore: 58,
    industryScore: 49,
    patternScore: 66,
    tradabilityScore: 72,
    operatorNote: 'Mixed management record; not a serial destroyer.',
    financialNote: 'Weak profitability, but capital markets access still open.',
    tradeWindow: '7–21 days',
    entryZone: '$0.78–$0.82',
    targetZone: '$0.96–$1.06',
    stopZone: '$0.72',
    status: 'Recovery Candidate',
    volume: '133.6K',
    chart: [
      { d: 'W1', p: 1.34 },
      { d: 'W2', p: 1.12 },
      { d: 'W3', p: 0.98 },
      { d: 'W4', p: 0.88 },
      { d: 'W5', p: 0.84 },
      { d: 'W6', p: 0.79 },
      { d: 'W7', p: 0.76 },
      { d: 'W8', p: 0.83 }
    ]
  },
  {
    ticker: 'GAME',
    company: 'GameSquare',
    price: 0.29,
    exchange: 'NASDAQ',
    industry: 'Media / Esports',
    daysUnderOne: 212,
    daysToDeadline: 167,
    bounceProbability: 39,
    delistingRisk: 77,
    complianceScore: 31,
    financialScore: 26,
    operatorScore: 43,
    industryScore: 45,
    patternScore: 34,
    tradabilityScore: 48,
    operatorNote: 'Late-stage compliance case with extension already used.',
    financialNote: 'Heavily dependent on capital markets support.',
    tradeWindow: '3–10 days',
    entryZone: '$0.26–$0.28',
    targetZone: '$0.34–$0.40',
    stopZone: '$0.23',
    status: 'High Delisting Risk',
    volume: '589K',
    chart: [
      { d: 'W1', p: 0.74 },
      { d: 'W2', p: 0.61 },
      { d: 'W3', p: 0.52 },
      { d: 'W4', p: 0.43 },
      { d: 'W5', p: 0.38 },
      { d: 'W6', p: 0.33 },
      { d: 'W7', p: 0.27 },
      { d: 'W8', p: 0.29 }
    ]
  },
  {
    ticker: 'FFAI',
    company: 'Faraday Future',
    price: 0.35,
    exchange: 'NASDAQ',
    industry: 'EV',
    daysUnderOne: 58,
    daysToDeadline: 176,
    bounceProbability: 54,
    delistingRisk: 62,
    complianceScore: 60,
    financialScore: 18,
    operatorScore: 35,
    industryScore: 24,
    patternScore: 59,
    tradabilityScore: 67,
    operatorNote: 'Speculative operator profile with higher pattern risk.',
    financialNote: 'Very weak business quality; movement is mostly capital-market driven.',
    tradeWindow: '2–8 days',
    entryZone: '$0.31–$0.34',
    targetZone: '$0.42–$0.50',
    stopZone: '$0.28',
    status: 'Management Action Likely',
    volume: '235.1M',
    chart: [
      { d: 'W1', p: 1.11 },
      { d: 'W2', p: 0.92 },
      { d: 'W3', p: 0.76 },
      { d: 'W4', p: 0.63 },
      { d: 'W5', p: 0.49 },
      { d: 'W6', p: 0.37 },
      { d: 'W7', p: 0.29 },
      { d: 'W8', p: 0.35 }
    ]
  },
  {
    ticker: 'ALXO',
    company: 'ALX Oncology',
    price: 0.96,
    exchange: 'NASDAQ',
    industry: 'Biotech',
    daysUnderOne: 29,
    daysToDeadline: 205,
    bounceProbability: 71,
    delistingRisk: 28,
    complianceScore: 82,
    financialScore: 44,
    operatorScore: 61,
    industryScore: 22,
    patternScore: 70,
    tradabilityScore: 75,
    operatorNote: 'Cleaner than average setup, but biotech remains structurally risky.',
    financialNote: 'Cash exists, but survival still relies on pipeline outcomes.',
    tradeWindow: '5–15 days',
    entryZone: '$0.92–$0.95',
    targetZone: '$1.05–$1.15',
    stopZone: '$0.88',
    status: 'Recovery Candidate',
    volume: '1.8M',
    chart: [
      { d: 'W1', p: 1.48 },
      { d: 'W2', p: 1.27 },
      { d: 'W3', p: 1.14 },
      { d: 'W4', p: 1.03 },
      { d: 'W5', p: 0.98 },
      { d: 'W6', p: 0.94 },
      { d: 'W7', p: 0.93 },
      { d: 'W8', p: 0.96 }
    ]
  }
];

export const mockAlerts: Alert[] = [
  { id: '1', ticker: 'ALXO', message: 'ALXO moved within 4% of the $1 recovery line', severity: 'warning', createdAt: new Date().toISOString() },
  { id: '2', ticker: 'FFAI', message: 'FFAI volume expanded more than 2.5x average', severity: 'info', createdAt: new Date().toISOString() },
  { id: '3', ticker: 'GAME', message: 'GAME remains late-stage after extension window', severity: 'critical', createdAt: new Date().toISOString() },
  { id: '4', ticker: 'TELA', message: 'TELA created a tighter support band near $0.78', severity: 'info', createdAt: new Date().toISOString() }
];

export const mockWatchlist = ['TELA', 'ALXO'];
